[project]
name = "workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.1.0",
    "dlt[duckdb,workspace]>=1.22.1",
    "graphviz>=0.21",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "nbqa>=1.9.1",
    "pandas>=3.0.1",
    "pip>=26.0.1",
    "yapf>=0.43.0",
]
